CREATE DATABASE VEHICLEDB
---SCEMA FOR SALES----
CREATE SCHEMA SALES
---TABLE FOR SALES.CUSTOMER----

CREATE TABLE SALES.CUSTOMER(
CUSTOMER_ID   INT PRIMARY KEY,
FIRST_NAME    VARCHAR(50),
LAST_NAME     VARCHAR(50),
PHONE         VARCHAR(10),
EMAIL         VARCHAR(50) UNIQUE ,
STREET        VARCHAR(50),
CITY          VARCHAR(50),
STATE         VARCHAR(50),
ZIP_CODE      VARCHAR(50)
)
---TABLE FOR SALES.STORES---

CREATE TABLE SALES.STORES(
STORE_ID      INT PRIMARY KEY,
STORE_NAME    VARCHAR(50),
PHONE         VARCHAR(10),
EMAIL         VARCHAR(50) UNIQUE ,
STREET        VARCHAR(50),
CITY          VARCHAR(50),
STATE         VARCHAR(50),
ZIP_CODE      VARCHAR(50)
)
----TABLE FOR SALES.STAFFS----

CREATE TABLE SALES.STAFFS(
STAFF_ID     INT PRIMARY KEY,
FIRST_NAME   VARCHAR(50),
LAST_NAME    VARCHAR(50),
EMAIL        VARCHAR(50) UNIQUE,
PHONE        VARCHAR(10) UNIQUE,
ACTIVE       VARCHAR(50),
STORE_ID     INT,
MANAGER_ID  INT ,
CONSTRAINT FK_ST_ID FOREIGN KEY  (STORE_ID) REFERENCES SALES.STORES(STORE_ID)
)

---TABLE FOR SALES.ORDER----

CREATE TABLE SALES.ORDERS(
ORDER_ID   INT PRIMARY KEY,
CUSTOMER_ID  INT,
ORDER_STATUS VARCHAR(50),
ORDER_DATE   VARCHAR(50),
REQUIRED_DATE DATE,
SHIPPED_DATE  DATE,
STORE_ID   INT,
STAFF_ID  INT 
CONSTRAINT FK_STORE_ID FOREIGN KEY (STORE_ID) REFERENCES SALES.STORES(STORE_ID),

CONSTRAINT FK_CUST_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES SALES.CUSTOMER(CUSTOMER_ID),

CONSTRAINT FK_STAFF_ID FOREIGN KEY (STAFF_ID)  REFERENCES  SALES.STAFFS(STAFF_ID)
)

---TABLE FOR SALES.ORDER_ITEM----

CREATE TABLE SALES.ORDER_ITEM(
ORDER_ID INT,
ITEM_ID INT PRIMARY KEY,
PRODUCCT_ID INT,
QUANTITY INT CHECK(QUANTITY>0),
LIST_PRICE INT CHECK(LIST_PRICE>0),
DISCOUNT INT,

CONSTRAINT FK_ORDER_ID FOREIGN KEY(ORDER_ID) REFERENCES SALES.ORDERS(ORDER_ID),

CONSTRAINT FK_PRODUCCT_ID FOREIGN KEY(PRODUCCT_ID) REFERENCES PRODUCTION.PRODUCTS(PRODUCCT_ID)
)



ALTER TABLE SALES.ORDER_ITEM
ADD ITEMS_AMOUNT AS((QUANTITY*lIST_PRICE)-DISCOUNT)

SELECT * FROM SALES.ORDER_ITEM 

-----PRODUCTION SHEMA----
CREATE SCHEMA PRODUCTION

CREATE TABLE PRODUCTION.CATEGORIES(
CATEGORY_ID     INT  PRIMARY KEY,
CATEGORY_NAME   VARCHAR(50),
)

CREATE TABLE PRODUCTION.BRANDS(
BRAND_ID    INT PRIMARY KEY,
BRAND_NAME   VARCHAR(50),
)

CREATE TABLE PRODUCTION.PRODUCTS(
PRODUCCT_ID INT PRIMARY KEY,
PRODUCT_NAME  VARCHAR(50),
BRAND_ID  INT,
CATEGORY_ID  INT,
MODEL_YEAR    INT,
LIST_PRICE    INT,

CONSTRAINT FK_BRAND_ID FOREIGN KEY(BRAND_ID) REFERENCES PRODUCTION.BRANDS(BRAND_ID),
CONSTRAINT FK_CATEGORY_ID FOREIGN KEY(CATEGORY_ID) REFERENCES PRODUCTION.CATEGORIES(CATEGORY_ID)

)

CREATE TABLE PRODUCTION.STOCKS(
STORE_ID    INT,
PRODUCCT_ID  INT,
QUANTITY    INT,
CONSTRAINT FK_STORES_ID FOREIGN KEY(STORE_ID) REFERENCES SALES.STORES(STORE_ID),
CONSTRAINT FK_PRODUCCT_ID FOREIGN KEY(PRODUCCT_ID) REFERENCES  PRODUCTION.PRODUCTS(PRODUCCT_ID)
)